
#FROM arm32v7/python:3.9-buster
#FROM python:3.9-buster
FROM python:3.7-slim-buster

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

#RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
# Python packages
RUN pip install --trusted-host pypi.python.org --default-timeout=100 -r requirements.txt

COPY . /code/app
RUN ls -lah
RUN ls -lah ./app
WORKDIR /code/app
RUN ls -lah

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
